### ISSUE TITLE
Robbery Final Quest Bug 

### ISSUE THREAD

**Issue by Pikabois** [KB-RolePlay/kbrp-issues#183]
### Description

When you are on the final robbery quest, sometimes it tells you that someone is already doing it and you have to wait -8000s to start 

### Reproduction steps

```bash
1. Get to the final quest
2. Try to start the robbery
```

**Comment by hugoheml** [comment]
Dear @Pikabois ,
An update has been released today, could you please retry and tell me informed if the problem is solved please?

**Comment by talarmin29** [comment]
@Pikabois the problem is solved please?

**Comment by hugoheml** [comment]
I close the issue, if the problem is not solved you can reopen it.
